<a href="https://colab.research.google.com/github/9kiwis/demo/blob/main/NumPy_%E1%83%A1%E1%83%90%E1%83%95%E1%83%90%E1%83%A0%E1%83%AF%E1%83%98%E1%83%A8%E1%83%9D%E1%83%94%E1%83%91%E1%83%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy სავარჯიშოები**

## სავარჯიშო 1: მასივის შექმნა
შექმენით 1D მასივი რიცხვებით 0-დან 9-მდე arange() ფუნქციის გამოყენებით.

In [1]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]



## სავარჯიშო 2: მასივის ფორმის შეცვლა
შექმენით 3x3 მატრიცა მნიშვნელობებით 0-დან 8-მდე reshape() ფუნქციის გამოყენებით.

In [2]:
arr = np.arange(9).reshape(3,3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## სავარჯიშო 3: მასივის ინდექსირება
შექმენით 1D მასივი მნიშვნელობებით 10-დან 19-მდე. ამოიღეთ ყველა კენტი რიცხვი ამ მასივიდან.

In [4]:
arr = np.arange(10,20)
კენტი_რიცხვები = arr[arr % 2 == 1]
print(კენტი_რიცხვები)

[11 13 15 17 19]


## სავარჯიშო 4: ლოგიკური ინდექსირება
შექმენით 2D მასივი ზომით (3,4), რომელიც შეიცავს შემთხვევით მნიშვნელობებს 0-სა და 1-ს შორის. ჩაანაცვლეთ ყველა მნიშვნელობა, რომელიც 0.5-ზე მეტია, 0-ით.


In [7]:
arr = np.random.rand(3,4)
print(arr)

arr[arr > 0.5] = 0
print(arr)

[[0.83048413 0.59805802 0.9782284  0.92754304]
 [0.68438154 0.51866191 0.9374974  0.0866327 ]
 [0.09619305 0.54328488 0.07212566 0.8621922 ]]
[[0.         0.         0.         0.        ]
 [0.         0.         0.         0.0866327 ]
 [0.09619305 0.         0.07212566 0.        ]]


## სავარჯიშო 5: მასივების მათემატიკა
შექმენით ორი მასივი ზომით (3, 3) შემთხვევითი მთელი რიცხვებით 1-დან 10-მდე. შეასრულეთ ელემენტებზე დაფუძნებული შეკრება, გამოკლება, გამრავლება და გაყოფა.

In [8]:
a = np.random.randint(1,11,size=(3,3))
b = np.random.randint(1,11,size=(3,3))

print("შეკრება:\n", a + b)
print("გამოკლება:\n", a - b)
print("გამრავლება:\n", a * b)
print("გაყოფა:\n", a / b)


შეკრება:
 [[ 9 15  8]
 [10 15 11]
 [14  5 13]]
გამოკლება:
 [[-1 -1 -4]
 [-6  1  9]
 [-2  1 -3]]
გამრავლება:
 [[20 56 12]
 [16 56 10]
 [48  6 40]]
გაყოფა:
 [[ 0.8         0.875       0.33333333]
 [ 0.25        1.14285714 10.        ]
 [ 0.75        1.5         0.625     ]]


## სავარჯიშო 6: მასივის სტატისტიკა
შექმენით 1D მასივი 20 შემთხვევითი მთელი რიცხვით 1-დან 100-მდე. გამოთვალეთ საშუალო, მედიანა, სტანდარტული გადახრა და დისპერსია.

In [14]:
arr = np.random.randint(1,101,size=20)

print("მასივი:", arr)
print("საშუალო:", np.mean(arr))
print("მედიანა:", np.median(arr))
print("სტანდარტული გადახრა:", np.std(arr))
print("დისპერსია:", np.var(arr))


მასივი: [21 65 39 78 50 61 27 88 14 69 32 48 16 95 18 12 34 49 14 56]
საშუალო: 44.3
მედიანა: 43.5
სტანდარტული გადახრა: 25.137820112332733
დისპერსია: 631.9100000000001


## სავარჯიშო 7: მასივის დალაგება
შექმენით 2D მასივი ზომით (5,5) შემთხვევითი მთელი რიცხვებით 1-დან 20-მდე. დაალაგეთ მასივი ორივე ღერძის გასწვრივ.


In [19]:
arr = np.random.randint(1,21,size=(5,5))
print("საწყისი მასივი:\n", arr)

print("დალაგებული სტრიქონების მიხედვით:\n", np.sort(arr, axis=1))
print("დალაგებული სვეტების მიხედვით:\n", np.sort(arr, axis=0))


საწყისი მასივი:
 [[11  6 11 17  1]
 [ 4 14  5 15 12]
 [ 2  1 16  7 14]
 [16 20 10  4  5]
 [ 6 18  2 20 11]]
დალაგებული სტრიქონების მიხედვით:
 [[ 1  6 11 11 17]
 [ 4  5 12 14 15]
 [ 1  2  7 14 16]
 [ 4  5 10 16 20]
 [ 2  6 11 18 20]]
დალაგებული სვეტების მიხედვით:
 [[ 2  1  2  4  1]
 [ 4  6  5  7  5]
 [ 6 14 10 15 11]
 [11 18 11 17 12]
 [16 20 16 20 14]]


## სავარჯიშო 8: მასივების გაერთიანება
შექმენით ორი 2D მასივი ზომით (3,3) და გააერთიანეთ ისინი ვერტიკალურად და ჰორიზონტალურად.

In [27]:
a = np.arange(3,12).reshape(3,3)
b = np.arange(9, 18).reshape(3, 3)

print("ვერტიკალურად გაერთიანება:\n", np.vstack((a, b)))
print("ჰორიზონტალურად გაერთიანება:\n", np.hstack((a, b)))


ვერტიკალურად გაერთიანება:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
ჰორიზონტალურად გაერთიანება:
 [[ 3  4  5  9 10 11]
 [ 6  7  8 12 13 14]
 [ 9 10 11 15 16 17]]


## სავარჯიშო 9: ბროდკასტინგი
შექმენით 3x4 მატრიცა შემთხვევითი მთელი რიცხვებით 1-დან 10-მდე. დაამატეთ 1D მასივი სიგრძით 4 ამ მატრიცის ყოველ სტრიქონს.


In [20]:
მატრიცა = np.random.randint(1,11,size=(3,4))
სტრიქონი = np.arange(1,5)

შედეგი = მატრიცა + სტრიქონი
print("საწყისი მატრიცა:\n", მატრიცა)
print("შედეგი ბროდკასტინგის შემდეგ:\n", შედეგი)

საწყისი მატრიცა:
 [[ 8  8 10  1]
 [10  9  6  8]
 [ 9  7  3  6]]
შედეგი ბროდკასტინგის შემდეგ:
 [[ 9 10 13  5]
 [11 11  9 12]
 [10  9  6 10]]


## სავარჯიშო 10: წრფივი ალგებრა
შექმენით ორი 3x3 მატრიცა შემთხვევითი მთელი რიცხვებით 1-დან 10-მდე. გამოთვალეთ მათი სკალარული ნამრავლი, საკუთრივი მნიშვნელობები და საკუთრივი ვექტორები.


In [30]:
a = np.random.randint(1,11,size=(3,3))
b = np.random.randint(1,11,size=(3,3))

print("მატრიცა A:\n", a)
print("მატრიცა B:\n", b)

სკალარული_ნამრავლი = np.dot(a,b)
print("სკალარული ნამრავლი:\n", სკალარული_ნამრავლი)

საკუთრივი_მნიშვნელობები, საკუთრივი_ვექტორები = np.linalg.eig(a)
print("A-ს საკუთრივი მნიშვნელობები:", საკუთრივი_მნიშვნელობები)
print("A-ს საკუთრივი ვექტორები:\n", საკუთრივი_ვექტორები)

მატრიცა A:
 [[7 6 1]
 [8 5 2]
 [7 7 2]]
მატრიცა B:
 [[ 4  9  8]
 [ 5 10 10]
 [ 2  8  3]]
სკალარული ნამრავლი:
 [[ 60 131 119]
 [ 61 138 120]
 [ 67 149 132]]
A-ს საკუთრივი მნიშვნელობები: [14.59593759  0.88123325 -1.47717085]
A-ს საკუთრივი ვექტორები:
 [[-0.53593267 -0.32179568  0.43881274]
 [-0.57553804  0.17302114 -0.71146129]
 [-0.61768288  0.93086585  0.54887723]]


## სავარჯიშო 11: მასივის მანიპულაცია
შექმენით 1D მასივი 10 შემთხვევითი მთელი რიცხვით 1-დან 100-მდე. იპოვეთ ყველა უნიკალური ელემენტი და მათი რაოდენობა.


In [33]:
arr = np.random.randint(1,101,size=10)
უნიკალური_ელემენტები, რაოდენობა = np.unique(arr, return_counts=True)

print("საწყისი მასივი:", arr)
print("უნიკალური ელემენტები:", უნიკალური_ელემენტები)
print("რაოდენობა:", რაოდენობა)

საწყისი მასივი: [84 30 91 84 89 95 11 62 12 52]
უნიკალური ელემენტები: [11 12 30 52 62 84 89 91 95]
რაოდენობა: [1 1 1 1 1 2 1 1 1]




## სავარჯიშო 12: გაფართოებული ინდექსირება
შექმენით 5x5 მატრიცა შემთხვევითი მთელი რიცხვებით 1-დან 25-მდე. ამოიღეთ ამ მატრიცის განაპირა ელემენტები.

In [34]:
მატრიცა = np.random.randint(1,26,size=(5,5))
print("საწყისი მატრიცა:\n", მატრიცა)

მიჯნა = np.concatenate([
    მატრიცა[0],  # ზედა სტრიქონი
    მატრიცა[-1],  # ქვედა სტრიქონი
    მატრიცა[1:-1, 0],  # პირველი სვეტი (კუთხეების გარდა)
    მატრიცა[1:-1, -1]  # ბოლო სვეტი (კუთხეების გარდა)
])

print("განაპირა ელემენტები:", მიჯნა)

საწყისი მატრიცა:
 [[14  5 16  4 10]
 [19 25 13 24  5]
 [16  4  9  7  6]
 [13 20 17 18 14]
 [12 20  8  7 16]]
განაპირა ელემენტები: [14  5 16  4 10 12 20  8  7 16 19 16 13  5  6 14]
